"""
JCR 2024 植物/农学/相关期刊权威白名单 (从 journal_rankings_2024_updated_deduplicated.csv 生成)
由 CSV 自动生成, 避免手写 502 个期刊错漏。
此名单用于 daily_update.py 期刊过滤的精确匹配层——JCR 收录的植物/农学期刊直接放行。
注意: 最终仍由 is_plant 内容校验兜底, 防止 JCR 池中同名医学期刊误收。
"""

import re

JOURNAL_JCR_PLANT = [
    # --- Plant Sciences (190) ---
    'Annual Review of Plant Biology',
    'Molecular Plant',
    'TRENDS IN PLANT SCIENCE',
    'Nature Plants',
    'Annual Review of Phytopathology',
    'PLANT CELL',
    'Plant Communications',
    'PLANT BIOTECHNOLOGY JOURNAL',
    'Journal of Integrative Plant Biology',
    'NEW PHYTOLOGIST',
    'Plant Nano Biology',
    'PHYTOCHEMISTRY REVIEWS',
    'CURRENT OPINION IN PLANT BIOLOGY',
    'PLANT PHYSIOLOGY',
    'Plant Stress',
    'Plant Diversity',
    'PLANT CELL AND ENVIRONMENT',
    'PLANT PHYSIOLOGY AND BIOCHEMISTRY',
    'PLANT JOURNAL',
    'JOURNAL OF EXPERIMENTAL BOTANY',
    'JOURNAL OF ECOLOGY',
    'aBIOTECH',
    'MOLECULAR PLANT PATHOLOGY',
    'CRITICAL REVIEWS IN PLANT SCIENCES',
    'BMC PLANT BIOLOGY',
    'Frontiers in Plant Science',
    'ENVIRONMENTAL AND EXPERIMENTAL BOTANY',
    'GM Crops & Food-Biotechnology in Agriculture',
    'Current Plant Biology',
    'PLANT CELL REPORTS',
    'Food and Energy Security',
    'JOURNAL OF PLANT GROWTH REGULATION',
    'PLANT DISEASE',
    'JOURNAL OF PLANT PHYSIOLOGY',
    'Plants-Basel',
    'PLANT SCIENCE',
    'PLANT AND CELL PHYSIOLOGY',
    'PLANT GROWTH REGULATION',
    'Plant Genome',
    'MYCORRHIZA',
    'PLANTA',
    'PLANT MOLECULAR BIOLOGY',
    'PHOTOSYNTHESIS RESEARCH',
    'PHYSIOLOGIA PLANTARUM',
    'ANNALS OF BOTANY',
    'Journal of Applied Research on Medicinal and Aromatic Plants',
    'JOURNAL OF NATURAL PRODUCTS',
    'PLANT BIOLOGY',
    'Plant Signaling & Behavior',
    'PLANT FOODS FOR HUMAN NUTRITION',
    'Rhizosphere',
    'Phytopathology Research',
    'MOLECULAR PLANT-MICROBE INTERACTIONS',
    'PHYTOCHEMISTRY',
    'Seed Biology',
    'PHYSIOLOGICAL AND MOLECULAR PLANT PATHOLOGY',
    'PHYSIOLOGY AND MOLECULAR BIOLOGY OF PLANTS',
    'Journal of Plant Interactions',
    'Botanical Studies',
    'PHYTOPATHOLOGY',
    'Journal of Soil Science and Plant Nutrition',
    'Vegetation Classification and Survey',
    'BOTANICAL REVIEW',
    'PRESLIA',
    'Journal of Systematics and Evolution',
    'PERSPECTIVES IN PLANT ECOLOGY EVOLUTION AND SYSTEMATICS',
    'FUNCTIONAL PLANT BIOLOGY',
    'SOUTH AFRICAN JOURNAL OF BOTANY',
    'AMERICAN JOURNAL OF BOTANY',
    'Phytobiomes Journal',
    'PHYTOCHEMICAL ANALYSIS',
    'Plant Pathology Journal',
    'PROTOPLASMA',
    'Quantitative Plant Biology',
    'Applications in Plant Sciences',
    'Plant Reproduction',
    'AoB Plants',
    'PLANT CELL TISSUE AND ORGAN CULTURE',
    'Journal of Cotton Research',
    'JOURNAL OF PLANT RESEARCH',
    'Alpine Botany',
    'Plant Direct',
    'ACTA PHYSIOLOGIAE PLANTARUM',
    'BOTANICAL JOURNAL OF THE LINNEAN SOCIETY',
    'Medicinal Plant Biology',
    'Theoretical and Experimental Plant Physiology',
    'TAXON',
    'JOURNAL OF PLANT BIOLOGY',
    'PLANTA MEDICA',
    'JOURNAL OF PLANT PATHOLOGY',
    'IN VITRO CELLULAR & DEVELOPMENTAL BIOLOGY-PLANT',
    'Facilities',
    'Science Technology and Society',
    'SEED SCIENCE RESEARCH',
    'Management',
    'Journal of Essential Oil Bearing Plants',
    'SOIL SCIENCE AND PLANT NUTRITION',
    'FLORA',
    'SABRAO Journal of Breeding and Genetics',
    'JOURNAL OF PLANT NUTRITION',
    'Plant Gene',
    'Plant Ecology & Diversity',
    'PHOTOSYNTHETICA',
    'AUSTRALIAN SYSTEMATIC BOTANY',
    'PLANT SYSTEMATICS AND EVOLUTION',
    'Plant Physiology Reports',
    'Plant Biotechnology Reports',
    'INTERNATIONAL JOURNAL OF PLANT SCIENCES',
    'Records of Natural Products',
    'Advances in Weed Science',
    'Journal of Crop Science and Biotechnology',
    'PhytoKeys',
    'CANADIAN JOURNAL OF PLANT PATHOLOGY',
    'Egyptian Journal of Botany',
    'Tropical Plant Pathology',
    'TURKISH JOURNAL OF BOTANY',
    'BRYOLOGIST',
    'JOURNAL OF PLANT BIOCHEMISTRY AND BIOTECHNOLOGY',
    'Fottea',
    'Willdenowia',
    'Journal of Berry Research',
    'Tropical Plant Biology',
    'LICHENOLOGIST',
    'Phytochemistry Letters',
    'PLANT MOLECULAR BIOLOGY REPORTER',
    'NEW ZEALAND JOURNAL OF BOTANY',
    'ECONOMIC BOTANY',
    'PLANT BIOSYSTEMS',
    'Botany Letters',
    'Notulae Botanicae Horti Agrobotanici Cluj-Napoca',
    'ACTA AGROBOTANICA',
    'Plant Ecology and Evolution',
    'Wspolczesna Onkologia-Contemporary Oncology',
    'ANNALS OF THE MISSOURI BOTANICAL GARDEN',
    'JOURNAL OF ASIAN NATURAL PRODUCTS RESEARCH',
    'PLANT SPECIES BIOLOGY',
    'Brazilian Journal of Botany',
    'Botany',
    'Hepatic Oncology',
    'Journal of Cancer Research and Therapeutics',
    'eCancerMedicalScience',
    'Plant Health Progress',
    'PHYTON-INTERNATIONAL JOURNAL OF EXPERIMENTAL BOTANY',
    'Invasive Plant Science and Management',
    'JOURNAL OF HERBS SPICES AND MEDICINAL PLANTS',
    'FOLIA GEOBOTANICA',
    'JOURNAL OF GENERAL PLANT PATHOLOGY',
    'PhytoFrontiers',
    'JOURNAL OF PHYTOPATHOLOGY',
    'JOURNAL OF BRYOLOGY',
    'Plant Biotechnology',
    'AUSTRALASIAN PLANT PATHOLOGY',
    'RUSSIAN JOURNAL OF PLANT PHYSIOLOGY',
    'NORDIC JOURNAL OF BOTANY',
    'Botanica Serbica',
    'Acta Botanica Brasilica',
    'Phytotaxa',
    'ARCHIVES OF PHYTOPATHOLOGY AND PLANT PROTECTION',
    'TAIWANIA',
    'GRANA',
    'NOVA HEDWIGIA',
    'HERZOGIA',
    'PAKISTAN JOURNAL OF BOTANY',
    'TUEXENIA',
    'ADANSONIA',
    'Annali di Botanica',
    'TELOPEA',
    'Journal of Medicinal Plants and By-products',
    'NOVON',
    'Indian Journal of Natural Products and Resources',
    'BOTHALIA',
    'BLUMEA',
    'International Journal of Phytopathology',
    'GAYANA BOTANICA',
    'Modern Phytomorphology',
    'Turczaninowia',
    'HASELTONIA',
    'ACTA BIOLOGICA CRACOVIENSIA SERIES BOTANICA',
    'Acta Phytotaxonomica et Geobotanica',
    'Scientific Papers-Series B-Horticulture',
    'CALDASIA',
    'ANALES DEL JARDIN BOTANICO DE MADRID',
    'BANGLADESH JOURNAL OF BOTANY',
    'IHERINGIA SERIE BOTANICA',
    'CASTANEA',
    'Plant Root',
    'PHYTOPROTECTION',
    'RHODORA',
    'Gorteria',
    'Zeitschrift fur Arznei- & Gewurzpflanzen',
    # --- Agronomy (102) ---
    'POSTHARVEST BIOLOGY AND TECHNOLOGY',
    'Agronomy for Sustainable Development',
    'Agricultural Water Management',
    'FIELD CROPS RESEARCH',
    'Plant Phenomics',
    'INDUSTRIAL CROPS AND PRODUCTS',
    'Rice Science',
    'Smart Agricultural Technology',
    'Crop Journal',
    'Crop and Environment',
    'EUROPEAN JOURNAL OF AGRONOMY',
    'Rice',
    'PLANT AND SOIL',
    'Global Change Biology Bioenergy',
    'Frontiers in Agronomy',
    'Agriculture-Basel',
    'IRRIGATION SCIENCE',
    'Agronomy-Basel',
    'Gesunde Pflanzen',
    'Turkish Journal of Agriculture and Forestry',
    'GRASS AND FORAGE SCIENCE',
    'JOURNAL OF AGRONOMY AND CROP SCIENCE',
    'JOURNAL OF PLANT NUTRITION AND SOIL SCIENCE',
    'Frontiers of Agricultural Science and Engineering',
    'International Journal of Wine Business Research',
    'Crop Protection',
    'WEED SCIENCE',
    'in silico Plants',
    'PLANT PATHOLOGY',
    'WEED RESEARCH',
    'Grassland Research',
    'AGROFORESTRY SYSTEMS',
    'International Journal of Plant Production',
    'Grass Research',
    'BREEDING SCIENCE',
    'POTATO RESEARCH',
    'Italian Journal of Agronomy',
    'Paddy and Water Environment',
    'AGRONOMY JOURNAL',
    'Sugar Tech',
    'MYCOBIOLOGY',
    'OCL-Oilseeds and Fats Crops and Lipids',
    'CROP SCIENCE',
    'EUROPEAN JOURNAL OF PLANT PATHOLOGY',
    'PHYTOPATHOLOGIA MEDITERRANEA',
    'CEREAL RESEARCH COMMUNICATIONS',
    'Crops',
    'EXPERIMENTAL AGRICULTURE',
    'PLANT SOIL AND ENVIRONMENT',
    'Archives of Agronomy and Soil Science',
    'ACTA AGRICULTURAE SCANDINAVICA SECTION B-SOIL AND PLANT SCIENCE',
    'Advances in Agriculture',
    'AMERICAN JOURNAL OF POTATO RESEARCH',
    'Czech Journal of Genetics and Plant Breeding',
    'PLANT BREEDING',
    'International Agrophysics',
    'WEED TECHNOLOGY',
    'IRRIGATION AND DRAINAGE',
    'International Journal of Agronomy',
    'Agrosystems Geosciences & Environment',
    'NEW ZEALAND JOURNAL OF CROP AND HORTICULTURAL SCIENCE',
    'WEED BIOLOGY AND MANAGEMENT',
    'Journal of Crop Improvement',
    'COMMUNICATIONS IN SOIL SCIENCE AND PLANT ANALYSIS',
    'PLANT PROTECTION SCIENCE',
    'PLANT PRODUCTION SCIENCE',
    'JOURNAL OF PLANT PROTECTION RESEARCH',
    'ACTA SCIENTIARUM-AGRONOMY',
    'Journal of Seed Science',
    'Journal of Agricultural Extension',
    'AGRICULTURAL RESEARCH',
    'Journal of Agriculture and Environment for International Development',
    'Crop Breeding and Applied Biotechnology',
    'Crop Forage & Turfgrass Management',
    'CANADIAN JOURNAL OF PLANT SCIENCE',
    'Romanian Agricultural Research',
    'Journal fur Kulturpflanzen',
    'BIOTECHNOLOGIE AGRONOMIE SOCIETE ET ENVIRONNEMENT',
    'Scientific Papers-Series A-Agronomy',
    'Agrivita',
    'Asian Journal of Agriculture and Development',
    'SAINS TANAH',
    'Agrociencia Uruguay',
    'Range Management and Agroforestry',
    'AGRONOMIA MESOAMERICANA',
    'Journal of Agricultural & Food Information',
    'Chilean Journal of Agricultural & Animal Sciences',
    'Terra Latinoamericana',
    'Egyptian Journal of Agronomy',
    'JOURNAL OF THE AMERICAN POMOLOGICAL SOCIETY',
    'Revista Brasileira de Ciencias Agrarias-Agraria',
    'Revista de Agricultura Neotropical',
    'Revista Fitotecnia Mexicana',
    'TROPICAL AGRICULTURE',
    'Ciencias Agronomicas',
    'Revista de Ciencias Agricolas',
    'Revista de la Facultad de Agronomia de la Universidad del Zulia',
    'WasserWirtschaft',
    'Agritech',
    'Revista Agrogeoambiental',
    'Temas Agrarios',
    'Philippine Journal of Crop Science',
    # --- Additional (210) ---
    'Nature Reviews Genetics',
    'Nature',
    'Science',
    'Cell',
    'Nature Biotechnology',
    'eScience',
    'Nature Methods',
    'Nature Genetics',
    'Cell Research',
    'Innovation',
    'Science Bulletin',
    'Nature Cell Biology',
    'Trends in Cell Biology',
    'Trends in Ecology & Evolution',
    'National Science Review',
    'Molecular Cell',
    'Trends in Genetics',
    'Nature Protocols',
    'Nature Communications',
    'Trends in Biotechnology',
    'Nucleic Acids Research',
    'Journal Of Advanced Research',
    'Biotechnology Advances',
    'Science Advances',
    'Global Change Biology',
    'Biological Reviews',
    'Annual Review of Ecology Evolution and Systematics',
    'Research',
    'Cellular & Molecular Biology Letters',
    'International Journal of Biological Sciences',
    'Genome Biology',
    'Proceedings Of The National Academy Of Sciences Of The United States Of America',
    'Developmental Cell',
    'Horticulture Research',
    'Embo Journal',
    'Phytomedicine',
    'Molecular Horticulture',
    'Genes & Development',
    'Molecular Systems Biology',
    'Current Biology',
    'PLOS Biology',
    'Journal of Genetics and Genomics',
    'Current Opinion in Biotechnology',
    'Cell Reports',
    'Scientific Data',
    'Molecules and Cells',
    'Journal of Cell Biology',
    'EMBO Reports',
    'Horticultural Plant Journal',
    'Journal of Molecular Cell Biology',
    'Agricultural and Forest Meteorology',
    'Systematic Biology',
    'Genome Research',
    'Journal of Ethnopharmacology',
    'Molecular Biology and Evolution',
    'Communications Biology',
    'Genetics',
    'Forestry Research',
    'International Journal of Molecular Sciences',
    'New Biotechnology',
    'Pharmaceutical Biology',
    'Biological Research',
    'Journal of Forestry Research',
    'Molecules',
    'BMC Biology',
    'Journal of Molecular Biology',
    'Forest Ecosystems',
    'Plant Methods',
    'Current Opinion in Cell Biology',
    'Ecology',
    'European Journal of Cell Biology',
    'Theoretical and Applied Genetics',
    'Gigascience',
    'Journal of Biotechnology',
    'Journal of Plant Ecology',
    'Molecular Ecology',
    'Scientific Reports',
    'BMC Genomics',
    'Forest Ecology and Management',
    'Journal of Ethnobiology and Ethnomedicine',
    'PLOS Genetics',
    'Tree Physiology',
    'Development',
    'Open Biology',
    'Plants People Planet',
    'PLOS Computational Biology',
    'BMC Biotechnology',
    'Frontiers in Physiology',
    'Journal of Phycology',
    'Rna Biology',
    'Evolutionary Applications',
    'Forestry',
    'Biotechnology Journal',
    'Cell Biology International',
    'Functional & Integrative Genomics',
    'Biology Letters',
    'Current Issues in Molecular Biology',
    'Genomics',
    'Molecular Breeding',
    'Seed Science and Technology',
    'DNA Research',
    'Genome Biology and Evolution',
    'Molecular Biology Reports',
    'Vegetable Research',
    'Annals of Forest Science',
    'Biotechnology and Applied Biochemistry',
    'BMC Molecular and Cell Biology',
    'European Journal of Forest Research',
    'Journal of Vegetation Science',
    'Molecular and Cellular Biology',
    'Molecular Biology of The Cell',
    'Applied Vegetation Science',
    'Aquatic Botany',
    'DNA and Cell Biology',
    'Evolution',
    'Journal of Experimental Biology',
    'PLOS One',
    'Biotechnology Progress',
    'Forests',
    'Molecular Biotechnology',
    'Ornamental Plant Research',
    'Physiological Genomics',
    'Algae',
    'Biology of The Cell',
    'Ecology and Evolution',
    'Journal of Evolutionary Biology',
    'Journal of Plant Diseases and Protection',
    'Biotechnology Letters',
    'Developmental Biology',
    'Evolutionary Ecology',
    'Molecular Genetics and Genomics',
    'Proceedings Of The Indian National Science Academy',
    'Evolution & Development',
    'Vegetation History and Archaeobotany',
    'Journal of Forestry',
    'Journal of Molecular Evolution',
    'Euphytica',
    'European Journal of Phycology',
    'Evolutionary Biology',
    'New Forests',
    'Plant Ecology',
    'Review of Palaeobotany and Palynology',
    'Biologia',
    'Omics-A Journal of Integrative Biology',
    'Tree Genetics & Genomes',
    'Canadian Journal of Forest Research',
    'Cryptogamie Algologie',
    'Evolutionary Bioinformatics',
    'Phytoparasitica',
    'Scandinavian Journal of Forest Research',
    'Botanica Marina',
    'Current Genomics',
    'Forest Science',
    'Integrative Biology',
    'Phycologia',
    'International Journal of Developmental Biology',
    'Palynology',
    'Australian Forestry',
    'Chinese Science Bulletin-Chinese',
    'Forest Products Journal',
    'Molecular Biology',
    'Journal of Forest Research',
    'Current Science',
    'Forest Pathology',
    'Ornamental Horticulture-Revista Brasileira De Horticultura Ornamental',
    'Silvae Genetica',
    'American Fern Journal',
    'Annales Botanici Fennici',
    'Australian Journal of Botany',
    'Biologia Plantarum',
    'Cryptogamie Bryologie',
    'Development Genes and Evolution',
    'International Forestry Review',
    'Journal of Aquatic Plant Management',
    'Kew Bulletin',
    'Phytocoenologia',
    'Southern Forests-A Journal of Forest Science',
    'Acta Botanica Mexicana',
    'Acta Societatis Botanicorum Poloniae',
    'Annual Plant Reviews Online',
    'Bangladesh Journal of Plant Taxonomy',
    'Forestry Chronicle',
    'Indian Journal of Genetics and Plant Breeding',
    'Journal of The Torrey Botanical Society',
    'Korean Journal of Plant Taxonomy',
    'Plant Science Today',
    'Systematic Botany',
    'Acta Botanica Croatica',
    'Australasian Plant Disease Notes',
    'Boletin De La Sociedad Argentina De Botanica',
    'Botanical Sciences',
    'Bradleya',
    'Brittonia',
    'Candollea',
    'Forest Systems',
    'Hacquetia',
    'Indian Journal of Traditional Knowledge',
    'Israel Journal of Plant Sciences',
    'Journal of Applied Botany and Food Quality',
    'Journal of Forest Economics',
    'Journal of Plant Registrations',
    'Mediterranean Botany',
    'Plant Genetic Resources-Characterization and Utilization',
    'American Scientist',
    'Propagation of Ornamental Plants',
    'Technology And Innovation',
    'Indian Journal of Experimental Biology',
    'Elife',
    'Genetic Resources and Crop Evolution',
    'Maydica',
]
JOURNAL_JCR_PLANT_LOWER = {j.lower() for j in JOURNAL_JCR_PLANT}


def _normalize(name):
    """归一化期刊名: 小写、去冠词、去标点/空格，用于鲁棒匹配。
    例: 'The Plant Journal' -> 'plantjournal'; 'PLANT CELL' -> 'plantcell'
    'The Plant Cell' 与 'PLANT CELL' 归一化后一致。
    """
    n = name.lower().strip()
    # 去冠词前缀
    for art in ('the ', 'a ', 'an '):
        if n.startswith(art):
            n = n[len(art):]
    # 去所有非字母数字字符(保留字母数字)
    n = re.sub(r'[^a-z0-9]', '', n)
    return n


# 归一化后的集合, 用于鲁棒匹配
_JCR_NORM = {_normalize(j) for j in JOURNAL_JCR_PLANT}


def journal_in_jcr(journal_name):
    """判断期刊是否在 JCR 植物名单中 (大小写/冠词/标点不敏感)。"""
    if not journal_name or not journal_name.strip():
        return False
    low = journal_name.strip().lower()
    # 1) 精确小写匹配
    if low in JOURNAL_JCR_PLANT_LOWER:
        return True
    # 2) 归一化模糊匹配 (处理 The/大小写/破折号/连字符差异)
    norm = _normalize(journal_name)
    if norm and norm in _JCR_NORM:
        return True
    return False